# Generated by Django 5.1.15 on 2026-05-10 20:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pentesters', '0001_initial'),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cover_message', models.TextField()),
                ('proposed_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proposed_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('SHORTLISTED', 'Shortlist'), ('ACCEPTED', 'Aceita'), ('REJECTED', 'Rejeitada'), ('WITHDRAWN', 'Retirada')], default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pentester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='pentesters.pentesterprofile')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='proposals.proposal')),
            ],
            options={
                'indexes': [models.Index(fields=['proposal', 'status'], name='application_proposa_d914dd_idx')],
                'constraints': [models.UniqueConstraint(fields=('proposal', 'pentester'), name='application_unique_pair')],
            },
        ),
    ]
