# Generated by Django 5.1.15 on 2026-05-10 20:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pentesters', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('scope_md', models.TextField()),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('budget_currency', models.CharField(default='BRL', max_length=3)),
                ('budget_kind', models.CharField(choices=[('FIXED', 'Fixo'), ('HOURLY', 'Por hora'), ('TBD', 'A combinar')], max_length=10)),
                ('duration_weeks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PUBLISHED', 'Publicada'), ('CLOSED', 'Fechada'), ('ARCHIVED', 'Arquivada')], default='DRAFT', max_length=10)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Pública'), ('PRIVATE', 'Privada')], default='PUBLIC', max_length=8)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialties', models.ManyToManyField(blank=True, related_name='proposals', to='pentesters.specialty')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('status', 'PUBLISHED')), fields=['status', '-published_at'], name='prop_status_pub_idx'), models.Index(fields=['tenant'], name='prop_tenant_idx')],
            },
        ),
    ]
