# Generated by Django 5.1.15 on 2026-05-10 20:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('COMPANY', 'Empresa'), ('INDIVIDUAL', 'Pentester')], max_length=12)),
                ('legal_name', models.CharField(max_length=200)),
                ('document', models.CharField(max_length=20)),
                ('document_kind', models.CharField(choices=[('CNPJ', 'CNPJ'), ('CPF', 'CPF')], max_length=4)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('VERIFIED', 'Verificado'), ('SUSPENDED', 'Suspenso')], default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['type', 'status'], name='tenants_ten_type_bb3311_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'document_kind'), name='tenant_document_unique')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MEMBER', 'Member'), ('BILLING', 'Billing')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'tenant'), name='membership_unique')],
            },
        ),
    ]
