# Generated by Django 5.1.15 on 2026-05-10 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('actor_ua', models.TextField(blank=True, default='')),
                ('tenant_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('object_type', models.CharField(max_length=64)),
                ('object_id', models.BigIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('prev_hash', models.BinaryField(blank=True, null=True)),
                ('self_hash', models.BinaryField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'occurred_at'], name='audit_audit_event_t_a6e18a_idx'), models.Index(fields=['tenant_id', 'occurred_at'], name='audit_audit_tenant__5831f4_idx')],
            },
        ),
    ]
