# Generated by Django 5.1.15 on 2026-06-22 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='favorite',
            new_name='favorites_f_user_id_ec7f89_idx',
            old_name='favorites_f_user_id_e1edd9_idx',
        ),
    ]
